version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: finamics.settings.dev
    SECRET_KEY: nosecret
    IMAGE_REPO_NAME: finamics
    IMAGE_TAG: dev
    ECR_ID: 257766425177

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pip install -U awscli
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
